version: '3'

services:
  app:
    build:
      context: app
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
    command: /bin/sh -c "while sleep 1000; do :; done" # override to disable app (e.g., for development)
